PRODUCT_VERSION_MAJOR = 1
PRODUCT_VERSION_MINOR = 0

ifeq ($(EUNOIA_VERSION_APPEND_TIME_OF_DAY),true)
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    EUNOIA_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set EUNOIA_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef EUNOIA_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "EUNOIA_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^EUNOIA_||g')
        EUNOIA_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(EUNOIA_BUILDTYPE)),)
    EUNOIA_BUILDTYPE := UNOFFICIAL
    EUNOIA_EXTRAVERSION :=
endif

ifeq ($(EUNOIA_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        EUNOIA_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

EUNOIA_VERSION_SUFFIX := $(EUNOIA_BUILD_DATE)-$(EUNOIA_BUILDTYPE)$(EUNOIA_EXTRAVERSION)-$(EUNOIA_BUILD)

# Internal version
EUNOIA_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(EUNOIA_VERSION_SUFFIX)

# Display version
EUNOIA_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(EUNOIA_VERSION_SUFFIX)
